benchmarking/benchmarks/benchmarks.py, benchmarking/driver/benchmark_driver.py, benchmarking/frameworks/caffe2/caffe2.py
Pass the backend parameter to the framework binary.
=> pass command to the binary

benchmarking/get_connected_androids.py
Change the way to get the connected android phones. Support multiple phones of the same kind.
=> Filter out all logging messages

benchmarking/benchmarks/benchmarks.py, benchmarking/frameworks/oculus/oculus.py, benchmarking/platforms/android/android_driver.py, benchmarking/platforms/android/android_platform.py, benchmarking/platforms/host/host_platform.py, benchmarking/platforms/platform_base.py
Support adding shared libraries to the Oculus backend.
=> Support adding shared libraries to the Oculus backend

benchmarking/repo_driver.py, benchmarking/run_bench.py, benchmarking/utils/utilities.py
In this way, we can make sure that the python called in all scripts are the same.
=> Pass the specified python in the command line to the child scripts it calls

benchmarking/driver/benchmark_driver.py, benchmarking/harness.py
Check that the framework specified in the json file and the one specified in the command line matches
=> Assert if the framework specified in the command line does not match the one specified in the json file

benchmarking/driver/benchmark_driver.py, benchmarking/harness.py
If cooldown is specified in json, it takes precedence over the command line argument.
=> Cooldown in json

benchmarking/driver/benchmark_driver.py, benchmarking/frameworks/caffe2/caffe2.py, benchmarking/reporters/remote_reporter/remote_reporter.py
Modified the operator data flow to allow for generic, non-numeric values to be stored in the data structure and reported remotely as a new entry for an operator. This new entry will register as a new metric and display its value in the "info_string" field.
=> Added support for (non-numeric) information fields for each operator

benchmarking/driver/benchmark_driver.py
As in the title. Added mean and standard deviation to the metrics reported as part of the summary statistics for a series of values. Both metrics are manually calculated and add no new dependencies.
=> Added mean and standard deviation to the reported summary statistics

benchmarking/frameworks/caffe2/caffe2.py, benchmarking/frameworks/framework_base.py
Refactor caffe2 to extract the common run method to the base class
=>  Refactor caffe2 to extract the common run method to the base class

benchmarking/frameworks/caffe2/caffe2.py, benchmarking/frameworks/framework_base.py
Remove delay from method names, since the collected data may not be delay any more (stacked)
=> Remove delay from method names, since the collected data may not be delay any more

benchmarking/driver/benchmark_driver.py, benchmarking/frameworks/caffe2/caffe2.py, benchmarking/frameworks/framework_base.py, benchmarking/frameworks/frameworks.py, benchmarking/frameworks/tflite/tflite.py, benchmarking/harness.py, benchmarking/repo_driver.py, benchmarking/reporters/remote_reporter/remote_reporter.py, benchmarking/utils/build_program.py, specifications/frameworks/tflite/android/build.sh, specifications/models/tflite/mobilenet_v1/mobilenet_v1_1.0_244_quant.json
This is a stacked PR. Please wait till the previous PRs are landed before reviewing this one.
=> Add TFLite framework

benchmarking/frameworks/caffe2/caffe2.py
Still need to handle the old data format
=> Remove assertion

benchmarking/driver/benchmark_driver.py, benchmarking/frameworks/caffe2/caffe2.py, benchmarking/frameworks/framework_base.py, benchmarking/harness.py, benchmarking/platforms/android/android_platform.py, benchmarking/platforms/platform_base.py, benchmarking/reporters/remote_reporter/remote_reporter.py, benchmarking/utils/monsoon_power.py, benchmarking/utils/subprocess_with_logger.py, specifications/models/caffe2/squeezenet/squeezenet_power.json
The initial setup to support power metrics with monsoon power monitor
=> Add support to extract power metric with monsoon power monitor

benchmarking/frameworks/framework_base.py, benchmarking/frameworks/tflite/tflite.py, specifications/models/caffe2/bvlc_alexnet/bvlc_alexnet.json, specifications/models/caffe2/bvlc_googlenet/bvlc_googlenet.json, specifications/models/caffe2/bvlc_reference_caffenet/bvlc_reference_caffenet.json, specifications/models/caffe2/bvlc_reference_rcnn_ilsvrc13/bvlc_reference_rcnn_ilsvrc13.json, specifications/models/caffe2/densenet121/densenet121.json, specifications/models/caffe2/inception_v1/inception_v1.json, specifications/models/caffe2/inception_v2/inception_v2.json, specifications/models/caffe2/resnet50/resnet50.json, specifications/models/caffe2/shufflenet/shufflenet.json, specifications/models/caffe2/squeezenet/squeezenet.json, specifications/models/caffe2/squeezenet/squeezenet_power.json, specifications/models/caffe2/style_transfer/style_transfer.json, specifications/models/caffe2/vgg16/vgg16.json, specifications/models/caffe2/vgg19/vgg19.json, specifications/models/tflite/mobilenet_v1/mobilenet_v1_1.0_244_quant.json
Two changes:
1. Add arguments support for tflite
2. Use variables for iter and warmup fields
=>  Add arguments support for tflite

benchmarking/benchmarks/benchmarks.py, benchmarking/driver/benchmark_driver.py, benchmarking/frameworks/framework_base.py, benchmarking/platforms/android/android_platform.py, benchmarking/platforms/host/host_platform.py, benchmarking/utils/subprocess_with_logger.py, specifications/models/caffe2/shufflenet/shufflenet.json
The commit has been tested locally: (1) timeout in json with android platform (2) timeout in argument with android platform (3) timeout in json with host platform (4) timeout in argument with host platform.
=> add timeout option and kill the job when it takes too long time

benchmarking/platforms/android/android_platform.py, benchmarking/utils/subprocess_with_logger.py
Refine the flow to be more robust on different environments.
=> Refine the power benchmark flow

specifications/models/caffe2/mobilenet_v2/mobilenet_v2_quant.json, specifications/models/caffe2/mobilenet_v2/mobilenet_v2_quant_1_thread.json, specifications/models/caffe2/mobilenet_v2/mobilenet_v2_quant_taskset_c.json, specifications/models/caffe2/mobilenet_v2/mobilenet_v2_quant_taskset_f0.json, specifications/models/caffe2/mobilenet_v2/mobilenet_v2_taskset_f0_quant.json, specifications/models/tflite/mobilenet_v2/mobilenet_v2_1.0_224_quant.json, specifications/models/tflite/mobilenet_v2/mobilenet_v2_1.0_224_quant_taskset_c.json, specifications/models/tflite/mobilenet_v2/mobilenet_v2_1.0_224_quant_taskset_f0.json, specifications/models/tflite/mobilenet_v2/mobilenet_v2_1.0_224_taskset_f0.json
Currently, the paths for the model files are paths pointing to my local disk. Will update those once we upload the appropriate models to s3. Sending this out to confirm the benchmark files have the right parameters.
=> Add benchmark json files for quantized models.

specifications/models/caffe2/resnet50_quant_arm_neon/resnet50_quant_taskset_c.json, specifications/models/caffe2/resnet50_quant_arm_neon/resnet50_quant_taskset_f0.json, specifications/models/tflite/resnet50_v2/resnet50_v2_quant_taskset_c.json, specifications/models/tflite/resnet50_v2/resnet50_v2_quant_taskset_f0.json
Added workloads for resnet50 quantized models for both caffe2 and tflite.
=> ResNet50 quant workloads.

specifications/models/caffe2/mobilenet_v2/mobilenet_v2_quant.json
new mobilenet v2 model path. To reproduce the results in https://code.fb.com/ml-applications/qnnpack/
=> new mobilenet v2 model

benchmarking/harness.py
change from app.status to status
=> change status

benchmarking/utils/subprocess_with_logger.py
Test plan:
verified with android app/binary runs.
=> Support python3.6 with the new timeout feature

.circleci/build.sh, .circleci/config.yml, .circleci/test.sh, .circleci/tests/test_pytorch.sh, .circleci/tests/test_tflite.sh, benchmarking/driver/benchmark_driver.py, benchmarking/repo_driver.py, benchmarking/run_bench.py, benchmarking/utils/utilities.py
The previous CI does not handle python3, this PR supports it. It also addresses several issues in the previous CI script. Also, it intentionally add some bugs in the code to expose issues in various scenarios.
=> Add CI on python3

.gitignore
Summary: as title
Differential Revision: D13683173
=> ignore pytest coverage auto-generated file
